apiVersion: v1
kind: Pod
metadata:
  name: tweets
  labels:
    name: tweets
spec:
  containers:
  - name: myapp
    image: tweet_go
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 3000

