version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL="postgresql+asyncpg://user:password@db:5432/booksdb"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booksdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: